name: Update Dev Server Action
on:
  push:
    branches:
    - development
    - Demo

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: rsync deployments
      uses: burnett01/rsync-deployments@4.1
      with:
        switches: -avzr --exclude "run" --exclude "node_modules" --delete
        path: Server/
        remote_path: /var/realityflow/development
        remote_host: ada.mrl.ai
        remote_user: realityflow
        remote_key: ${{ secrets.ADA_REALITYFLOW_SSH_SECRET }}